# main site metadata and titles
site_name: MEDI{CODE}
site_description: Teaching Clinicians to Code
site_author: Dr Anchit Chandran
site_url: https://medicode.info/

# copyright information which is shown in the footer
copyright: Copyright &copy; 2023 Anchit Chandran Ltd.

# these lines configure the 'GitHub repo' widget on the top right
repo_url: https://github.com/anchit-chandran/medicode-website
repo_name: anchit-chandran/medicode-website

# `mkdocs serve` serves the documentation at custom port
dev_addr: "127.0.0.1:8001"


nav:
  - "index.md"
  - About: 
    - 'about.md'
    - What does learning to code actually mean?: 'learning-to-code.md'
  - Course Details: 'details.md'
  - Team: 'team.md'
  - FAQs: 'faq.md'
  - Contact Us: 'contact.md'

theme:
  name: material 
  custom_dir: overrides
  logo: _assets/_images/logo.svg
  favicon: _assets/_images/logo.svg
  features:
    - navigation.expand
    - header.autohide
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - toc.follow

  palette:
    scheme: dark
  font:
    text: Montserrat
    code: Roboto Mono

watch:
  - overrides

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/medic_ode
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/medic_ode/

